package com.ybrikman.ping

class DedupeSpec extends BaseDedupeSpec with PingScalaTestComponents

class BigPipeSpec extends BaseBigPipeSpec with PingScalaTestComponents

class BigPipeTimingSpec extends BaseBigPipeTimingSpec with PingScalaTestComponents